version: "2.0"
services:
  installer:
    build: ./docker-images/installer
    container_name: magento1_installer
    networks:
      - custom_magento1
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: pw
      MAGENTO_ROOT: /var/www/html/web
    volumes_from:
      - nginx
    volumes:
      - ./bin/installer/install.sh:/bin/install.sh
    links:
      - "mysql:mysql"
      - "maildev:maildev"
    entrypoint: /bin/install.sh
  nginx:
    image: nginx:1.11.8
    container_name: magento1_nginx
    networks:
      - custom_magento1
    ports:
      - "80:80"
      - "443:443"
    volumes:
          - ./logs/nginx:/var/log/nginx
          - ./config/ssl/cert.pem:/etc/nginx/ssl/cert.pem
          - ./config/ssl/cert.key:/etc/nginx/ssl/cert.key
          - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./config/nginx/sites-enabled/default.conf.tmpl:/etc/default.conf.tmpl
          - ./config/nginx/includes:/etc/nginx/includes
          - ./config/nginx/custom-locations:/etc/nginx/custom-locations
          - ./bin/nginx/nginx.sh:/bin/nginx.sh
          - ./bin/substitute-env-vars.sh:/bin/substitute-env-vars.sh
    volumes_from:
          - php7
    links:
      - "mysql:mysql"
      - "maildev:maildev"
    entrypoint: /bin/nginx.sh
  php7:
    build: ./docker-images/php7
    container_name: magento1_php7
    networks:
      - custom_magento1
    links:
      - "cache:rediscache"
      - "sessions:redissession"
      - "mysql:mysql"
      - "maildev:maildev"
  cache:
    image: redis:latest
    container_name: magento1_redis_cache
    networks:
    - custom_magento1
  sessions:
    image: redis:latest
    container_name: magento1_redis_sessions
    networks:
    - custom_magento1
  mysql:
    image: mysql:5.5
    container_name: magento1_mysql
    networks:
      - custom_magento1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/dump:/etc/dump
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: magento1_phpmyadmin
    networks:
        - custom_magento1
    ports:
      - "8081:80"
    links:
      - "mysql:mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: 3306
  maildev:
    image: djfarrelly/maildev
    container_name: magento1_maildev
    networks:
        - custom_magento1
    ports:
     - 8282:80
networks:
    custom_magento1:
        ipam:
            driver: default
            config:
                - subnet: 172.80.0.0/24